### ISSUE TITLE
Strange Loop Milestone

### ISSUE THREAD

**Issue by brianhempel** [ravichugh/sketch-n-sketch#75]
### Novel Stuff
- [x] Basic Replicate
- [ ] Solver
- [ ] Value Locking
- [ ] More constraints (?)
### Other Improvements
- [x] Remove "Edit Code"
- [ ] Bounding box for groups
- [ ] Drag group by dragging parts
- [ ] Group pluck fix
- [x] Parse Errors
- [ ] Type System
- [x] Nicer runtime error handling (?)
- [ ] Text box shape
- [ ] Layers (?)
- [x] Upgrade to Elm 0.17

**Comment by brianhempel** [comment]
Goals and direction are slightly different now.
